In [2]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
# dot product of 2 vectors
a = np.array([2,3])
b = np.array([4,4])
a_dot_b = np.dot(a,b)
a_dot_b

20

In [7]:
c = np.array([40,20,35])
d = np.array([53,24,68])

c_dot_d = np.dot(c,d)
c_dot_d

4980

In [8]:
# cross product of two vectors
a = np.array([2,3])
b = np.array([4,4])

a_cross_b = np.cross(a,b)
a_cross_b

array(-4)

In [9]:
c = np.array([40,20,35])
d = np.array([53,24,68])

c_dot_d = np.cross(c,d)
c_dot_d

array([ 520, -865, -100])

In [10]:
# projection of two vectors
a = np.array([2,5])
v = np.array([8,-6])
# magnitude of v vector
magnitude_of_v= np.sqrt(sum(v**2))

projection_of_a_on_v = (np.dot(a,v)/magnitude_of_v**2) * v
projection_of_a_on_v

array([-1.12,  0.84])

In [11]:
a = np.array([23,45,62])
v = np.array([45,82,67])

# magnitude of v vector
magnitude_of_v= np.sqrt(sum(v**2))
projection_of_a_on_v = (np.dot(a,v)/magnitude_of_v**2) * v
projection_of_a_on_v

array([30.18242937, 54.99909352, 44.93828373])