In [1]:
import numpy as np

In [4]:
# Creating a matrix 
matrix_1 = np.array([[2,3],[6,7]])
matrix_1

array([[2, 3],
       [6, 7]])

In [6]:
# shape of a matrix (row, col)
matrix_1.shape

(2, 2)

In [7]:
# dimension of a matrix 1d,2d, 3d
matrix_1.ndim

2

In [8]:
matrix_2 = np.array([[10,20,34],[20,30,36],[30,40,38]], dtype="float")
matrix_2

array([[10., 20., 34.],
       [20., 30., 36.],
       [30., 40., 38.]])

In [9]:
matrix_2.shape

(3, 3)

In [10]:
matrix_2.ndim

2

In [12]:
# transpose of matrix 2
mt = matrix_2.T
mt

array([[10., 20., 30.],
       [20., 30., 40.],
       [34., 36., 38.]])

In [13]:
# Create matrix with random values
matrix_3 = np.random.rand(3,3)
matrix_3

array([[0.18071367, 0.77598715, 0.47042883],
       [0.06071329, 0.20121177, 0.31845808],
       [0.04503642, 0.29628455, 0.45291583]])

In [16]:
# creating matrix with random integer
matrix_4 = np.random.randint(50, size=(4,5))
matrix_4

array([[ 6, 40,  4, 32, 13],
       [31,  9, 27, 49, 24],
       [48, 31, 42,  5, 21],
       [ 7,  6, 35, 48, 35]])

In [19]:
# create a matrix with all the values 1
matrix_5 = np.ones((2,3), dtype="int8")
matrix_5

array([[1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [20]:
# create an identity matrix
matrix_6 = np.identity(4, dtype="int8")
matrix_6

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int8)

In [26]:
# create a matrix with all zeros.
matrix_7 = np.zeros((4,5))
matrix_7

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
mat = np.random.randint(50, size=(4,5))
mat

array([[49,  5, 26, 12, 14],
       [47, 21, 27, 32, 39],
       [ 4, 39, 34, 22, 43],
       [26, 23, 35, 20,  3]])

In [28]:
mat.T

array([[49, 47,  4, 26],
       [ 5, 21, 39, 23],
       [26, 27, 34, 35],
       [12, 32, 22, 20],
       [14, 39, 43,  3]])