In [3]:
import numpy as np

In [4]:
# matrix addition
a = np.array([[2,3],[10,5]], dtype="int8")
b = np.array([[10,5],[20,4]], dtype="int8")
c = a+b
c

array([[12,  8],
       [30,  9]], dtype=int8)

In [5]:
# matrix subtraction
d = a-b
d

array([[ -8,  -2],
       [-10,   1]], dtype=int8)

In [6]:
# matrix multiplication a*b scalar
e = a*b
e

array([[ 20,  15],
       [-56,  20]], dtype=int8)

In [7]:
# matrix scalar multiplcation
f = 2*a
f

array([[ 4,  6],
       [20, 10]], dtype=int8)

In [8]:
g = np.multiply(a,b)
g

array([[ 20,  15],
       [-56,  20]], dtype=int8)

In [11]:
# multiply 2 matrices
A = np.random.randint(5, size=(2,3))
B = np.random.randint(5, size = (3,2))
C = np.dot(A,B)

print(A)
print(B)
print(C)

[[4 1 3]
 [0 4 4]]
[[0 4]
 [1 3]
 [1 4]]
[[ 4 31]
 [ 8 28]]


In [12]:
# matrix dot muliplication
c = np.dot(a, b)
c

array([[ 80,  22],
       [-56,  70]], dtype=int8)