In [5]:
# Importing the dependent libraries
import numpy as np

from sklearn.datasets import load_digits
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC


In [6]:
digits = load_digits()

In [26]:
X_train, X_test, Y_train, Y_test = train_test_split(digits.data, digits.target, test_size=0.3, random_state=42, stratify=digits.target)

In [27]:
# APerformance of logistic regression
lg = LogisticRegression()
lg.fit(X_train, Y_train)
lg.score(X_test, Y_test)

/home/kamrul/Desktop/python-ws/machine_learning/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9574074074074074

In [28]:
# Performance of support vector machine
svm = SVC()
svm.fit(X_train, Y_train)
svm.score(X_test, Y_test)

0.9888888888888889

In [29]:
# Performance using random forest
rf = RandomForestClassifier(n_estimators=10)
rf.fit(X_train, Y_train)
rf.score(X_test, Y_test)

0.9444444444444444

In [30]:
# Use Kfold to divide data
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [32]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [33]:
def get_score(model, X_train, X_test, Y_train, Y_test):
    model.fit(X_train, Y_train)
    return model.score(X_test, Y_test)


In [34]:
get_score(LogisticRegression(), X_train, X_test, Y_train, Y_test)

/home/kamrul/Desktop/python-ws/machine_learning/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9574074074074074

In [35]:
get_score(SVC(), X_train, X_test, Y_train, Y_test)

0.9888888888888889

In [36]:
get_score(RandomForestClassifier(), X_train, X_test, Y_train, Y_test)

0.9703703703703703

In [37]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [57]:
scores_l = []
scores_svm = []
scores_rf = []
# splitting the data by Stratified K Fold
for train_index, test_index in kf.split(digits.data):
    X_train, X_test, Y_train, Y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    # performance of logistic regression
    scores_l.append(get_score(LogisticRegression(), X_train, X_test, Y_train, Y_test))
    # performance of Support Vector machine
    scores_svm.append(get_score(SVC(), X_train, X_test, Y_train, Y_test))
    # performance of Random Forest
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=20), X_train, X_test, Y_train, Y_test))
    

/home/kamrul/Desktop/python-ws/machine_learning/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/kamrul/Desktop/python-ws/machine_learning/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://s

In [58]:
scores_l

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [59]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [60]:
scores_rf

[0.9232053422370617, 0.9415692821368948, 0.9081803005008348]

In [61]:
print(f"Average score of Logistic Regression = {sum(scores_l)/len(scores_l)}")

Average score of Logistic Regression = 0.9265442404006677


In [62]:
print(f"Average score of SVM = {sum(scores_svm)/len(scores_svm)}")

Average score of SVM = 0.9677239844184752


In [63]:
print(f"Average score of Random Forest = {sum(scores_rf)/len(scores_rf)}")

Average score of Random Forest = 0.9243183082915971


In [64]:
# User Kfold directly
from sklearn.model_selection import cross_val_score

In [65]:
cross_val_score(LogisticRegression(), digits.data, digits.target)

/home/kamrul/Desktop/python-ws/machine_learning/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/kamrul/Desktop/python-ws/machine_learning/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://s

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [66]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [67]:
cross_val_score(RandomForestClassifier(), digits.data, digits.target)

array([0.93611111, 0.9       , 0.96100279, 0.95821727, 0.91643454])

In [68]:
# Parameter tuning
cross_val_score(RandomForestClassifier(n_estimators=5), digits.data, digits.target)

array([0.85      , 0.80555556, 0.8718663 , 0.92200557, 0.82451253])

In [69]:
cross_val_score(RandomForestClassifier(n_estimators=10), digits.data, digits.target)

array([0.90555556, 0.82777778, 0.93036212, 0.93036212, 0.8718663 ])

In [70]:
cross_val_score(RandomForestClassifier(n_estimators=15), digits.data, digits.target)

array([0.9       , 0.86944444, 0.94428969, 0.92479109, 0.90807799])

In [71]:
cross_val_score(RandomForestClassifier(n_estimators=30), digits.data, digits.target)

array([0.92777778, 0.88055556, 0.94707521, 0.94986072, 0.91086351])