In [1]:
# importing the dependent libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [9]:
# importing the dataset
dataset = pd.read_csv("Data.csv")
X = dataset.iloc[:, :-1].values # row 0 - n(all rows) columns first to second last 0 - n-1
y = dataset.iloc[:, -1].values # all row last columns

In [3]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [4]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [10]:
# some information about the dataset
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 452.0+ bytes


In [11]:
# statistical measures of the dataset
dataset.describe()

,Age,Salary
count,9.000000,9.000000
mean,38.777778,63777.777778
std,7.693793,12265.579662
min,27.000000,48000.000000
25%,35.000000,54000.000000
50%,38.000000,61000.000000
75%,44.000000,72000.000000
max,50.000000,83000.000000


In [13]:
# Taking care of missing data
# for large dataset delete missing row, for small dataset fill the missing  value mean mode median
# we will fill missing  age & salary by average salary by sklearn imputer
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy="mean")
imputer.fit(X[:,1:3]) # fill missing value of age and salary by mean ( all row, only age col 1 and salary col 2)
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [14]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [19]:
# Encoding categorical data Country column
# One hot Encoding
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [20]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [21]:
# Encoding dependent varibale purched column using label encoder
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [22]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [23]:
# Split the dataset into train and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=1)

In [24]:
print(X_train)

[[0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]
 [1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 1.0 38.0 61000.0]]


In [25]:
print(X_test)

[[0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 0.0 1.0 38.77777777777778 52000.0]]


In [26]:
print(y_train)

[0 1 1 0 1 0 1 0]


In [27]:
print(y_test)

[1 0]


In [28]:
# Feature scaling
# Normalization ->  works when data distribution is normal range 0-1
# Standarisation -> works on every situation range from -3 to +3 standard deviation
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
# apply standardisation only features not encoded columns (vategorical variable) cause they are already within the range
X_train[:, 3:] = sc.fit_transform(X_train[:,3:])
X_test[:, 3:] = sc.fit_transform(X_test[:,3:])

In [29]:
print(X_train)

[[0.0 1.0 0.0 1.4810949949635102 1.5511947816430594]
 [1.0 0.0 0.0 -0.21158499928050145 0.15293469678171007]
 [1.0 0.0 0.0 -0.4719973060872725 -0.6335866009527988]
 [1.0 0.0 0.0 0.6998580745431972 0.5898909733008817]
 [0.0 0.0 1.0 -1.5136465333143565 -1.5074991539911422]
 [0.0 1.0 0.0 -1.1230280731042 -0.9831516221681362]
 [1.0 0.0 0.0 1.2206826881567392 1.201629760427722]
 [0.0 0.0 1.0 -0.08137884587711594 -0.3714128350412959]]


In [30]:
print(X_test)

[[0.0 1.0 0.0 1.0000000000000058 1.0]
 [0.0 0.0 1.0 -0.9999999999999942 -1.0]]
