In [1]:
"""Numpy - Numerical Python"""

'Numpy - Numerical Python'

In [3]:
import numpy as np

In [4]:
# list vs numpy time taken
from time import process_time


In [9]:
# time taken by a ist
python_list = [i for i in range(100000)]
start_time = process_time()
python_list = [i+5 for i in range(100000)]
end_time = process_time()
print(f"time taken = {end_time-start_time}")


time taken = 0.010858476999999755


In [10]:
numpy_array = np.array([i for i in range(100000)])
start_time = process_time()
numpy_array+=5
end_time = process_time()
print(f"time taken = {end_time-start_time}")

time taken = 0.0004960379999996434


In [12]:
# Numpy arrays
list1 = [1,2,3,4,5]
print(list1)
print(type(list1))

[1, 2, 3, 4, 5]
<class 'list'>


In [13]:
np_arr = np.array([1,2,3,4,5])
print(np_arr)
print(type(np_arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [18]:
# 1d array
a = np.array([1,2,3,4,5])
a.shape

(5,)

In [19]:
# 2d array
b= np.array([(1,2,3,4),(5,6,7,8)])
b.shape

(2, 4)

In [23]:
c = np.array([(1,2,3),(4,5,6)], dtype=int)
c

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
# create numpy array of zeros
x = np.zeros((4,5), dtype=int)
x

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [26]:
# create numpy array of ones
y = np.ones((4,5), dtype=int)
y

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [30]:
# create and identity matrix
z = np.identity(5, dtype=int)
z

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [29]:
# create array at a particular value
z = np.full((5,4), 5)
z

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [32]:
# create a numpy array with random values
a = np.random.random((3,4))
a

array([[0.62846208, 0.08538018, 0.80035485, 0.56953133],
       [0.42548522, 0.71695444, 0.26969688, 0.19341025],
       [0.26956641, 0.87595026, 0.00462813, 0.2683838 ]])

In [33]:
# create a numpy array with random integer
b = np.random.randint(2,10, (3,4))
b

array([[2, 3, 9, 6],
       [9, 7, 3, 7],
       [2, 8, 7, 4]])

In [34]:
# array of evenly spaced value
c = np.linspace(10, 30, 5)
c

array([10., 15., 20., 25., 30.])

In [35]:
# array of eveley spaced value with steps
d = np.arange(10,30, 5)
d

array([10, 15, 20, 25])

In [36]:
# convert a list to a numpy array
list2 = [10,20,30,40,50]
e = np.asarray(list2)
e

array([10, 20, 30, 40, 50])

In [38]:
# analyzing numpy array
f = np.random.randint(10,50, (5,5))
print(f)
print(f.shape)

[[34 32 22 18 33]
 [18 14 20 25 24]
 [38 18 45 39 20]
 [49 18 13 26 18]
 [42 10 21 22 17]]
(5, 5)


In [40]:
print(f.ndim)


2


In [42]:
# Checking number of elements in the arr
print(f.size)

25


In [43]:
# checking data type
print(f.dtype)

int64


In [45]:
# Mathematical operation on a np array
list1 = [1,2,3,4,5]
list2 = [6,7,8,9, 10]
print(list1+list2)

a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
print(a+b)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 7  9 11 13 15]


In [46]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
print(a-b)

[-5 -5 -5 -5 -5]


In [47]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
print(a*b)

[ 6 14 24 36 50]


In [48]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
print(a/b)

[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [53]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = np.dot(a,b)
c

130

In [54]:
print(np.add(a,b))

[ 7  9 11 13 15]


In [55]:
# array manupulation
arr = np.random.randint(0,10,(2,3))
arr

array([[8, 3, 8],
       [8, 9, 1]])

In [56]:
# transpose
trans = np.transpose(arr)
trans

array([[8, 8],
       [3, 9],
       [8, 1]])

In [57]:
trans.T

array([[8, 3, 8],
       [8, 9, 1]])

In [58]:
a = np.random.randint(0,10,(2,3))
a

array([[8, 8, 6],
       [0, 7, 8]])

In [61]:
# reshape the array
b = a.reshape(3,2)
b

array([[8, 8],
       [6, 0],
       [7, 8]])