In [1]:
# imporint the dependent libraries
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv("homeprices.csv")
df.head()

,area,price
0,2600,550000
1,3000,565000
2,3200,610000
3,3600,680000
4,4000,725000


In [3]:
model = linear_model.LinearRegression()
model.fit(df[["area"]], df.price)

LinearRegression()

In [4]:
model.coef_

array([135.78767123])

In [5]:
model.intercept_

180616.43835616432

In [7]:
model.predict([[3000]])

/home/kamrul/Desktop/python-ws/machine_learning/venv/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([587979.45205479])

In [8]:
# save model using pickle
import pickle

In [9]:
with open("model_pickle", "wb") as f:
    pickle.dump(model, f)


In [10]:
# load the model from pickle file
with open("model_pickle", "rb") as f:
    mp = pickle.load(f)


In [11]:
mp.predict([[3000]])

/home/kamrul/Desktop/python-ws/machine_learning/venv/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([587979.45205479])

In [21]:
# save model using joblib
import joblib

In [23]:
# Save the model in your file
joblib.dump(model, "model_joblib")

['model_joblib']

In [24]:
mj = joblib.load("model_joblib")

In [25]:
mj.predict([[3000]])

/home/kamrul/Desktop/python-ws/machine_learning/venv/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([587979.45205479])